# -*- coding: utf-8 -*-
"""P2-BasicFuzzyOperations.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KXSUmb29_3fgC-axcSqsM2aryQTnSfR5
"""

import  matplotlib.pyplot  as  plt 
import  numpy  as  np 

A=[]
B=[]
C=[]
AuB=[]
AuC=[]
BuC=[]
AnB=[]
AnC=[]
BnC=[]
nA=[]
nB=[]
nC=[]

X=np.arange(0,10,0.1)

for k in X:
  A.append(k/(k+2))
  B.append(2**(-k))
  C.append(1/(1+10*(k-2)**(2)))

for k in range(len(X)):
  AuB.append(max(A[k],B[k]))  
  AuC.append(max(A[k],C[k]))
  BuC.append(max(B[k],C[k]))
  AnB.append(min(A[k],B[k]))
  AnC.append(min(A[k],C[k]))
  BnC.append(min(B[k],C[k]))
  nA.append(1-A[k])
  nB.append(1-B[k])
  nC.append(1-C[k])


fig=plt.figure(figsize=(10,10),tight_layout=True)
fig.supylabel('Membership Degree')
fig.suptitle("Basic Fuzzy Operations")

plt.subplot(4,3,1)
plt.plot(X,A,'--y',X,[(1-A[k]) for k in range(len(X))],'#c4037a')
plt.title(r"$A & \bar{A} $")
plt.xlabel("Universe")
plt.ylabel("Complements")
plt.grid(True)

plt.subplot(4,3,2)
plt.plot(X,B,'--g',X,[(1-B[k]) for k in range(len(X))],'#c4037a')
plt.title(r"$B & \bar{B} $")
plt.xlabel("Universe")
plt.grid(True)

plt.subplot(4,3,3)
plt.plot(X,C,'--k',X,[(1-C[k]) for k in range(len(X))],'#c4037a')
plt.title(r"$C & \bar{C} $")
plt.xlabel("Universe")
plt.grid(True)

plt.subplot(4,3,4)
plt.plot(X,A,'--y',X,B,'--g',X,AuB,'#c4037a')
plt.title(r"$A \cup B$")
plt.xlabel("Universe")
plt.ylabel("Unions")
plt.grid(True)

plt.subplot(4,3,5)
plt.plot(X,A,'--y',X,C,'--k',X,AuC,'#c4037a')
plt.title(r"$A \cup C$")
plt.xlabel("Universe")
plt.grid(True)

plt.subplot(4,3,6)
plt.plot(X,B,'--g',X,C,'--k',X,BuC,'#c4037a')
plt.title(r"$B \cup C$")
plt.xlabel("Universe")
plt.grid(True)

plt.subplot(4,3,7)
plt.plot(X,A,'--y',X,B,'--g',X,AnB,'#c4037a')
plt.title(r"$A \cap B$")
plt.ylabel("Intersections")
plt.xlabel("Universe")
plt.grid(True)

plt.subplot(4,3,8)
plt.plot(X,A,'--y',X,C,'--k',X,AnC,'#c4037a')
plt.title(r"$A \cap C$")
plt.xlabel("Universe")
plt.grid(True)

plt.subplot(4,3,9)
plt.plot(X,B,'--g',X,C,'--k',X,BnC,'#c4037a')
plt.title(r"$B \cap C$")
plt.xlabel("Universe")
plt.grid(True)

plt.subplot(4,3,10)
plt.plot(X,A,'--y',X,nC,'--k',X,[max(nA[k],C[k]) for k in range(len(X))],'#c4037a')
plt.title(r"$\overline{ A\cap \overline{C} }$")
plt.xlabel("Universe")
plt.ylabel("Morgan Laws")
plt.grid(True)

plt.subplot(4,3,11)
plt.plot(X,nB,'--g',X,C,'--k',X,[max(B[k],nC[k]) for k in range(len(X))],'#c4037a')
plt.title(r"$\overline{ \overline{B}\cap C }$")
plt.xlabel("Universe")
plt.grid(True)

plt.subplot(4,3,12)
plt.plot(X,A,'--y',X,C,'--k',X,[min(nA[k],nC[k]) for k in range(len(X))],'#c4037a')
plt.title("$\overline{A \cup C}$")
plt.xlabel("Universe")
plt.grid(True)
plt.show()
